<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="/WEB-INF/views/layout/header.jsp"/>

<%--
    Register a new appointment (Requirement 2).

    Collects every field named in the scenario. The dentist and treatment
    lists come from the database, and the time slots are generated by
    SlotService for the chosen dentist and date, so a taken time cannot be
    selected.
--%>

<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<div class="page-head">
    <div>
        <h2 class="page-head__title">Register New Appointment</h2>
        <p class="page-head__sub">Enter the patient details and choose an available time slot.</p>
    </div>
    <a class="btn btn--ghost" href="${ctx}/admin/appointments">Back to list</a>
</div>

<c:if test="${not empty errors}">
    <div class="alert-bar alert-bar--error">
        <strong>Please correct the following:</strong>
        <ul>
            <c:forEach var="error" items="${errors}">
                <li><c:out value="${error}"/></li>
            </c:forEach>
        </ul>
    </div>
</c:if>

<%-- ---------- step 1: choose the dentist and the date ---------- --%>
<section class="panel search-panel">
    <div class="panel__body">
        <form class="search-row" method="get" action="${ctx}/admin/appointments/new">
            <div class="form-field form-field--grow">
                <label for="pickDoctor">Dentist <span class="required">*</span></label>
                <select class="input" id="pickDoctor" name="doctorId" onchange="this.form.submit()">
                    <option value="">Select a dentist</option>
                    <c:forEach var="doctor" items="${doctors}">
                        <option value="${doctor.doctorId}"
                                ${chosenDoctorId eq doctor.doctorId ? 'selected' : ''}>
                            <c:out value="${doctor.doctorName}"/> -
                            <c:out value="${doctor.specialization}"/>
                            (LKR ${doctor.formattedFee})
                        </option>
                    </c:forEach>
                </select>
            </div>
            <div class="form-field">
                <label for="pickDate">Date <span class="required">*</span></label>
                <input class="input" type="date" id="pickDate" name="date"
                       value="${chosenDate}" min="${today}" onchange="this.form.submit()">
            </div>
            <button class="btn btn--ghost" type="submit">Show Times</button>
        </form>
    </div>
</section>

<%-- ---------- step 2: the form itself ---------- --%>
<form method="post" action="${ctx}/admin/appointments/new" class="grid-2" id="appointmentForm">

    <input type="hidden" name="doctorId" value="${chosenDoctorId}">
    <input type="hidden" name="appointmentDate" value="${chosenDate}">
    <input type="hidden" name="appointmentTime" id="appointmentTime"
           value="<c:out value='${formTime}'/>">

    <div class="side-column">

        <section class="panel">
            <header class="panel__head">
                <h3>Patient Details</h3>
                <span class="badge badge--muted" id="patientBadge">New patient</span>
            </header>
            <div class="panel__body">

                <%-- Look up somebody who has been here before. The list comes
                     from /api/patients while the receptionist types, and one
                     click fills in the fields below. Retyping an address is
                     how the same person ends up in the system twice. --%>
                <div class="form-field patient-lookup">
                    <label for="patientLookup">Returning patient?</label>
                    <input class="input" type="search" id="patientLookup"
                           autocomplete="off"
                           placeholder="Search by name, telephone number or NIC">
                    <p class="hint">
                        Start typing to find an existing record, or leave this empty
                        and fill in the details below for a new patient.
                    </p>

                    <div class="lookup-results" id="lookupResults" hidden></div>
                </div>

                <div class="chosen-patient" id="chosenPatient" hidden>
                    <span>
                        Using the existing record for
                        <strong id="chosenPatientName"></strong>
                        <small id="chosenPatientVisits"></small>
                    </span>
                    <button type="button" class="link link--button" onclick="clearChosenPatient()">
                        Clear
                    </button>
                </div>

                <div class="form-row">
                    <div class="form-field">
                        <label for="appointmentNo">Appointment Number</label>
                        <input class="input input--readonly mono" type="text" id="appointmentNo"
                               value="${nextNumber}" readonly>
                        <p class="hint">Generated by the system. It cannot be edited.</p>
                    </div>
                    <div class="form-field">
                        <label for="nic">NIC Number</label>
                        <input class="input" type="text" id="nic" name="nic"
                               value="<c:out value='${formNic}'/>"
                               placeholder="199012345678" maxlength="12">
                    </div>
                </div>

                <div class="form-field">
                    <label for="patientName">Patient Name <span class="required">*</span></label>
                    <input class="input" type="text" id="patientName" name="patientName"
                           value="<c:out value='${formPatientName}'/>"
                           placeholder="Saman Kumara" minlength="3" maxlength="100" required>
                </div>

                <div class="form-field">
                    <label for="address">Address <span class="required">*</span></label>
                    <textarea class="input" id="address" name="address" rows="2"
                              placeholder="No 45, Galle Road, Colombo 03" required><c:out value="${formAddress}"/></textarea>
                </div>

                <div class="form-row">
                    <div class="form-field">
                        <label for="contactNumber">Contact Number <span class="required">*</span></label>
                        <input class="input" type="tel" id="contactNumber" name="contactNumber"
                               value="<c:out value='${formContact}'/>"
                               placeholder="0712345678" pattern="0[0-9]{9}" maxlength="10" required>
                        <p class="hint">A returning patient is matched on this number.</p>
                    </div>
                    <div class="form-field">
                        <label for="email">Email</label>
                        <input class="input" type="email" id="email" name="email"
                               value="<c:out value='${formEmail}'/>"
                               placeholder="patient@gmail.com">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-field">
                        <label for="gender">Gender</label>
                        <select class="input" id="gender" name="gender">
                            <option value="">Prefer not to say</option>
                            <option value="MALE" ${formGender eq 'MALE' ? 'selected' : ''}>Male</option>
                            <option value="FEMALE" ${formGender eq 'FEMALE' ? 'selected' : ''}>Female</option>
                            <option value="OTHER" ${formGender eq 'OTHER' ? 'selected' : ''}>Other</option>
                        </select>
                        <p class="hint">Optional. Recorded on the patient's file.</p>
                    </div>

                    <%-- How the booking reached the clinic. The daily report
                         is far more useful when walk-ins can be told apart
                         from booked slots. --%>
                    <div class="form-field">
                        <label for="bookingType">Appointment Type <span class="required">*</span></label>
                        <select class="input" id="bookingType" name="bookingType" required>
                            <option value="WALK_IN" ${formBookingType eq 'ONLINE' ? '' : 'selected'}>
                                Walk in - came to desk
                            </option>
                            <option value="ONLINE" ${formBookingType eq 'ONLINE' ? 'selected' : ''}>
                                Online - telephone
                            </option>
                        </select>
                    </div>
                </div>

            </div>
        </section>

        <section class="panel">
            <header class="panel__head"><h3>Appointment Details</h3></header>
            <div class="panel__body">

                <div class="form-field">
                    <label for="treatmentId">Treatment Type <span class="required">*</span></label>
                    <select class="input" id="treatmentId" name="treatmentId" required>
                        <option value="">Select a treatment</option>
                        <c:forEach var="treatment" items="${treatments}">
                            <option value="${treatment.treatmentId}"
                                    ${formTreatmentId eq treatment.treatmentId ? 'selected' : ''}>
                                <c:out value="${treatment.treatmentName}"/> -
                                LKR ${treatment.baseCost} (${treatment.estimatedMinutes} min)
                            </option>
                        </c:forEach>
                    </select>
                </div>

                <div class="form-field">
                    <label>Chosen Time <span class="required">*</span></label>
                    <p class="chosen-time" id="chosenTimeLabel">
                        <c:choose>
                            <c:when test="${not empty formTime}"><c:out value="${formTime}"/></c:when>
                            <c:otherwise>No time selected yet</c:otherwise>
                        </c:choose>
                    </p>
                    <p class="hint">Pick a green slot on the right.</p>
                </div>

                <div class="form-field">
                    <label for="notes">Notes</label>
                    <textarea class="input" id="notes" name="notes" rows="2"
                              placeholder="Anything the dentist should know"><c:out value="${formNotes}"/></textarea>
                </div>

                <div class="form-actions">
                    <a class="btn btn--ghost" href="${ctx}/admin/appointments">Cancel</a>
                    <button class="btn btn--primary" type="submit">Register Appointment</button>
                </div>

            </div>
        </section>
    </div>

    <%-- ---------- the generated slots ---------- --%>
    <div class="side-column">
        <section class="panel">
            <header class="panel__head">
                <h3>Available Times</h3>
                <span class="badge badge--muted">${chosenDate}</span>
            </header>
            <div class="panel__body">

                <c:choose>
                    <c:when test="${chosenDoctorId le 0}">
                        <div class="empty-state">
                            <p class="empty-state__title">Choose a dentist first</p>
                            <p class="empty-state__text">
                                Select a dentist and a date above, and the available
                                times for that day will appear here.
                            </p>
                        </div>
                    </c:when>

                    <c:when test="${empty slots}">
                        <div class="empty-state">
                            <p class="empty-state__title">Not working on this day</p>
                            <p class="empty-state__text">
                                This dentist has no working hours set for the chosen day.
                                Try another date, or ask an administrator to set the
                                working hours on the Schedule screen.
                            </p>
                        </div>
                    </c:when>

                    <c:otherwise>
                        <div class="slot-grid">
                            <c:forEach var="slot" items="${slots}">
                                <button type="button"
                                        class="slot-chip ${slot.available ? '' : 'slot-chip--booked'}"
                                        data-time="${slot.value}"
                                        onclick="selectSlot(this)">${slot.value}</button>
                            </c:forEach>
                        </div>

                        <div class="legend">
                            <span><i class="legend__dot legend__dot--free"></i> Available</span>
                            <span><i class="legend__dot legend__dot--booked"></i> Already booked</span>
                            <span><i class="legend__dot legend__dot--selected"></i> Selected</span>
                        </div>

                        <p class="hint">
                            A booked time cannot be selected. The server checks again
                            before saving, and the database refuses a duplicate as a
                            final safeguard.
                        </p>
                    </c:otherwise>
                </c:choose>

            </div>
        </section>
    </div>
</form>

<script src="${ctx}/assets/js/ui.js"></script>
<script>
    /* Shows the chosen time beside the form as well as in the hidden field. */
    document.addEventListener('click', function (event) {
        if (event.target.classList && event.target.classList.contains('slot-chip')
                && !event.target.classList.contains('slot-chip--booked')) {
            document.getElementById('chosenTimeLabel').textContent = event.target.dataset.time;
        }
    });

    document.getElementById('appointmentForm').addEventListener('submit', function (event) {
        if (!document.getElementById('appointmentTime').value) {
            event.preventDefault();
            showToast('Please choose a time slot before saving.', 'error');
        }
    });

    /* =================================================================
       Returning patient lookup.

       Calls the /api/patients web service while the receptionist types and
       fills the form from the record they pick. The request is delayed
       slightly after each keystroke, so typing a name sends one request
       rather than one per letter.
       ================================================================= */
    (function () {
        var lookup = document.getElementById('patientLookup');
        var results = document.getElementById('lookupResults');
        var timer = null;

        function hideResults() {
            results.hidden = true;
            results.innerHTML = '';
        }

        function message(text) {
            var line = document.createElement('p');
            line.className = 'lookup-empty';
            line.textContent = text;
            results.innerHTML = '';
            results.appendChild(line);
            results.hidden = false;
        }

        function show(patients) {
            results.innerHTML = '';

            patients.forEach(function (patient) {
                var row = document.createElement('button');
                row.type = 'button';
                row.className = 'lookup-row';

                var name = document.createElement('strong');
                name.textContent = patient.name;

                var detail = document.createElement('small');
                detail.textContent = patient.contactNumber
                        + (patient.nic ? '  |  ' + patient.nic : '')
                        + '  |  ' + patient.visits
                        + (patient.visits === 1 ? ' visit' : ' visits')
                        + '  |  last seen ' + patient.lastVisit;

                row.appendChild(name);
                row.appendChild(detail);

                /* Built with textContent rather than innerHTML, so a name
                   containing < or & is shown as text and never as markup. */
                row.addEventListener('click', function () {
                    fillFrom(patient);
                });

                results.appendChild(row);
            });

            results.hidden = false;
        }

        function fillFrom(patient) {
            document.getElementById('patientName').value = patient.name || '';
            document.getElementById('address').value = patient.address || '';
            document.getElementById('contactNumber').value = patient.contactNumber || '';
            document.getElementById('email').value = patient.email || '';
            document.getElementById('nic').value = patient.nic || '';
            document.getElementById('gender').value = patient.gender || '';

            document.getElementById('chosenPatientName').textContent = patient.name;
            document.getElementById('chosenPatientVisits').textContent =
                    ' - ' + patient.visits + (patient.visits === 1 ? ' visit' : ' visits')
                    + ', last seen ' + patient.lastVisit;
            document.getElementById('chosenPatient').hidden = false;

            var badge = document.getElementById('patientBadge');
            badge.textContent = 'Returning patient';
            badge.className = 'badge badge--success';

            lookup.value = '';
            hideResults();
            showToast(patient.name + "'s details were filled in.", 'success');
        }

        lookup.addEventListener('input', function () {
            var term = lookup.value.trim();
            clearTimeout(timer);

            if (term.length < 2) {
                hideResults();
                return;
            }

            timer = setTimeout(function () {
                fetch('${ctx}/api/patients?q=' + encodeURIComponent(term))
                    .then(function (response) {
                        if (!response.ok) {
                            throw new Error('lookup failed');
                        }
                        return response.json();
                    })
                    .then(function (data) {
                        if (!data.patients.length) {
                            message('No existing patient matched. Fill in the details below '
                                    + 'to register them as a new patient.');
                            return;
                        }
                        show(data.patients);
                    })
                    .catch(function () {
                        message('The patient search is unavailable. '
                                + 'Type the details in below instead.');
                    });
            }, 250);
        });

        /* Clicking anywhere else puts the list away. */
        document.addEventListener('click', function (event) {
            if (!results.contains(event.target) && event.target !== lookup) {
                hideResults();
            }
        });
    })();

    /* Goes back to entering a new patient by hand. */
    function clearChosenPatient() {
        ['patientName', 'address', 'contactNumber', 'email', 'nic', 'gender'].forEach(function (id) {
            document.getElementById(id).value = '';
        });
        document.getElementById('chosenPatient').hidden = true;

        var badge = document.getElementById('patientBadge');
        badge.textContent = 'New patient';
        badge.className = 'badge badge--muted';
    }
</script>

<jsp:include page="/WEB-INF/views/layout/footer.jsp"/>
