<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="/WEB-INF/views/layout/header.jsp"/>

<%--
    Register a new appointment (Requirement 2).

    Collects every field named in the scenario: appointment number, patient
    name, address, contact number, dentist, treatment type, date and time.
    The appointment number is generated by the system and shown read only so
    that staff cannot type a duplicate.
--%>

<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<div class="page-head">
    <div>
        <h2 class="page-head__title">Register New Appointment</h2>
        <p class="page-head__sub">Enter the patient details and choose an available time slot.</p>
    </div>
    <a class="btn btn--ghost" href="${ctx}/admin/appointments">Back to list</a>
</div>


<form class="grid-2" id="appointmentForm"
      onsubmit="showToast('This feature is not available in this version yet.', 'info'); return false;">

    <!-- ---------- left: the form ---------- -->
    <div class="side-column">

        <section class="panel">
            <header class="panel__head"><h3>Patient Details</h3></header>
            <div class="panel__body">

                <div class="form-row">
                    <div class="form-field">
                        <label for="appointmentNo">Appointment Number</label>
                        <input class="input input--readonly mono" type="text" id="appointmentNo"
                               value="APT-20260901-003" readonly>
                        <p class="hint">Generated by the system. It cannot be edited.</p>
                    </div>
                    <div class="form-field">
                        <label for="nic">NIC Number</label>
                        <input class="input" type="text" id="nic" placeholder="199012345678" maxlength="12">
                    </div>
                </div>

                <div class="form-field">
                    <label for="patientName">Patient Name <span class="required">*</span></label>
                    <input class="input" type="text" id="patientName" placeholder="Saman Kumara"
                           minlength="3" maxlength="100" required>
                </div>

                <div class="form-field">
                    <label for="address">Address <span class="required">*</span></label>
                    <textarea class="input" id="address" rows="2"
                              placeholder="No 45, Galle Road, Colombo 03" required></textarea>
                </div>

                <div class="form-row">
                    <div class="form-field">
                        <label for="contact">Contact Number <span class="required">*</span></label>
                        <input class="input" type="tel" id="contact" placeholder="0712345678"
                               pattern="0[0-9]{9}" maxlength="10" required>
                        <p class="hint">10 digits starting with 0, for example 0712345678</p>
                    </div>
                    <div class="form-field">
                        <label for="email">Email</label>
                        <input class="input" type="email" id="email" placeholder="patient@gmail.com">
                    </div>
                </div>

            </div>
        </section>

        <section class="panel">
            <header class="panel__head"><h3>Appointment Details</h3></header>
            <div class="panel__body">

                <div class="form-row">
                    <div class="form-field">
                        <label for="dentist">Dentist <span class="required">*</span></label>
                        <select class="input" id="dentist" required>
                            <option value="">Select a dentist</option>
                            <option value="1">Dr. Anura Jayasinghe - General Dentistry (LKR 1,500)</option>
                            <option value="2">Dr. Sanduni Fernando - Orthodontics (LKR 2,500)</option>
                            <option value="3">Dr. Kasun Silva - Oral Surgery (LKR 3,000)</option>
                            <option value="4">Dr. Malsha Weerasinghe - Pediatric (LKR 2,000)</option>
                        </select>
                    </div>
                    <div class="form-field">
                        <label for="treatment">Treatment Type <span class="required">*</span></label>
                        <select class="input" id="treatment" required>
                            <option value="">Select a treatment</option>
                            <option value="1">Consultation - LKR 0</option>
                            <option value="2">Scaling - LKR 4,500</option>
                            <option value="3">Filling - LKR 6,000</option>
                            <option value="4">Tooth Extraction - LKR 5,000</option>
                            <option value="5">Root Canal - LKR 25,000</option>
                            <option value="6">Crown Fitting - LKR 35,000</option>
                            <option value="7">Teeth Whitening - LKR 15,000</option>
                            <option value="8">Braces Fitting - LKR 85,000</option>
                        </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-field">
                        <label for="appointmentDate">Appointment Date <span class="required">*</span></label>
                        <input class="input" type="date" id="appointmentDate" value="2026-09-01"
                               min="2026-09-01" required>
                        <p class="hint">A date in the past cannot be selected.</p>
                    </div>
                    <div class="form-field">
                        <label for="appointmentTime">Appointment Time <span class="required">*</span></label>
                        <input class="input input--readonly" type="text" id="appointmentTime"
                               placeholder="Choose a slot on the right" readonly required>
                    </div>
                </div>

                <div class="form-field">
                    <label for="notes">Notes</label>
                    <textarea class="input" id="notes" rows="2"
                              placeholder="Anything the dentist should know before the visit"></textarea>
                </div>

                <div class="form-actions">
                    <a class="btn btn--ghost" href="${ctx}/admin/appointments">Cancel</a>
                    <button class="btn btn--primary" type="submit">Register Appointment</button>
                </div>

            </div>
        </section>
    </div>

    <!-- ---------- right: slot picker and summary ---------- -->
    <div class="side-column">

        <section class="panel">
            <header class="panel__head">
                <h3>Available Times</h3>
                <span class="badge badge--muted">01 Sep 2026</span>
            </header>
            <div class="panel__body">
                <div class="slot-grid">
                    <button class="slot-chip slot-chip--booked" type="button" data-time="09:00" onclick="selectSlot(this)">09:00</button>
                    <button class="slot-chip" type="button" data-time="09:30" onclick="selectSlot(this)">09:30</button>
                    <button class="slot-chip slot-chip--booked" type="button" data-time="10:00" onclick="selectSlot(this)">10:00</button>
                    <button class="slot-chip" type="button" data-time="10:30" onclick="selectSlot(this)">10:30</button>
                    <button class="slot-chip slot-chip--booked" type="button" data-time="11:00" onclick="selectSlot(this)">11:00</button>
                    <button class="slot-chip" type="button" data-time="11:30" onclick="selectSlot(this)">11:30</button>
                    <button class="slot-chip" type="button" data-time="12:00" onclick="selectSlot(this)">12:00</button>
                    <button class="slot-chip" type="button" data-time="13:30" onclick="selectSlot(this)">13:30</button>
                    <button class="slot-chip" type="button" data-time="14:00" onclick="selectSlot(this)">14:00</button>
                    <button class="slot-chip" type="button" data-time="14:30" onclick="selectSlot(this)">14:30</button>
                    <button class="slot-chip" type="button" data-time="15:30" onclick="selectSlot(this)">15:30</button>
                    <button class="slot-chip" type="button" data-time="16:00" onclick="selectSlot(this)">16:00</button>
                </div>

                <div class="legend">
                    <span><i class="legend__dot legend__dot--free"></i> Available</span>
                    <span><i class="legend__dot legend__dot--booked"></i> Booked</span>
                    <span><i class="legend__dot legend__dot--selected"></i> Selected</span>
                </div>
            </div>
        </section>

        <section class="panel">
            <header class="panel__head"><h3>Estimated Cost</h3></header>
            <div class="panel__body">
                <ul class="summary-list">
                    <li><span>Consultation fee</span><strong>LKR 1,500.00</strong></li>
                    <li><span>Treatment cost</span><strong>LKR 4,500.00</strong></li>
                    <li class="summary-list__total"><span>Estimated total</span><strong>LKR 6,000.00</strong></li>
                </ul>
                <p class="hint">The final bill is produced after the visit on the billing screen.</p>
            </div>
        </section>

    </div>
</form>

<script src="${ctx}/assets/js/ui.js"></script>

<jsp:include page="/WEB-INF/views/layout/footer.jsp"/>
