<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="/WEB-INF/views/layout/header.jsp"/>

<%--
    Register a new appointment (Requirement 2).

    Collects every field named in the scenario. The dentist and treatment
    lists come from the database, and the time slots are generated by
    SlotService for the chosen dentist and date, so a taken time cannot be
    selected.
--%>

<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<div class="page-head">
    <div>
        <h2 class="page-head__title">Register New Appointment</h2>
        <p class="page-head__sub">Enter the patient details and choose an available time slot.</p>
    </div>
    <a class="btn btn--ghost" href="${ctx}/admin/appointments">Back to list</a>
</div>

<c:if test="${not empty errors}">
    <div class="alert-bar alert-bar--error">
        <strong>Please correct the following:</strong>
        <ul>
            <c:forEach var="error" items="${errors}">
                <li><c:out value="${error}"/></li>
            </c:forEach>
        </ul>
    </div>
</c:if>

<%-- ---------- step 1: choose the dentist and the date ---------- --%>
<section class="panel search-panel">
    <div class="panel__body">
        <form class="search-row" method="get" action="${ctx}/admin/appointments/new">
            <div class="form-field form-field--grow">
                <label for="pickDoctor">Dentist <span class="required">*</span></label>
                <select class="input" id="pickDoctor" name="doctorId" onchange="this.form.submit()">
                    <option value="">Select a dentist</option>
                    <c:forEach var="doctor" items="${doctors}">
                        <option value="${doctor.doctorId}"
                                ${chosenDoctorId eq doctor.doctorId ? 'selected' : ''}>
                            <c:out value="${doctor.doctorName}"/> -
                            <c:out value="${doctor.specialization}"/>
                            (LKR ${doctor.formattedFee})
                        </option>
                    </c:forEach>
                </select>
            </div>
            <div class="form-field">
                <label for="pickDate">Date <span class="required">*</span></label>
                <input class="input" type="date" id="pickDate" name="date"
                       value="${chosenDate}" min="${today}" onchange="this.form.submit()">
            </div>
            <button class="btn btn--ghost" type="submit">Show Times</button>
        </form>
    </div>
</section>

<%-- ---------- step 2: the form itself ---------- --%>
<form method="post" action="${ctx}/admin/appointments/new" class="grid-2" id="appointmentForm">

    <input type="hidden" name="doctorId" value="${chosenDoctorId}">
    <input type="hidden" name="appointmentDate" value="${chosenDate}">
    <input type="hidden" name="appointmentTime" id="appointmentTime"
           value="<c:out value='${formTime}'/>">

    <div class="side-column">

        <section class="panel">
            <header class="panel__head"><h3>Patient Details</h3></header>
            <div class="panel__body">

                <div class="form-row">
                    <div class="form-field">
                        <label for="appointmentNo">Appointment Number</label>
                        <input class="input input--readonly mono" type="text" id="appointmentNo"
                               value="${nextNumber}" readonly>
                        <p class="hint">Generated by the system. It cannot be edited.</p>
                    </div>
                    <div class="form-field">
                        <label for="nic">NIC Number</label>
                        <input class="input" type="text" id="nic" name="nic"
                               value="<c:out value='${formNic}'/>"
                               placeholder="199012345678" maxlength="12">
                    </div>
                </div>

                <div class="form-field">
                    <label for="patientName">Patient Name <span class="required">*</span></label>
                    <input class="input" type="text" id="patientName" name="patientName"
                           value="<c:out value='${formPatientName}'/>"
                           placeholder="Saman Kumara" minlength="3" maxlength="100" required>
                </div>

                <div class="form-field">
                    <label for="address">Address <span class="required">*</span></label>
                    <textarea class="input" id="address" name="address" rows="2"
                              placeholder="No 45, Galle Road, Colombo 03" required><c:out value="${formAddress}"/></textarea>
                </div>

                <div class="form-row">
                    <div class="form-field">
                        <label for="contactNumber">Contact Number <span class="required">*</span></label>
                        <input class="input" type="tel" id="contactNumber" name="contactNumber"
                               value="<c:out value='${formContact}'/>"
                               placeholder="0712345678" pattern="0[0-9]{9}" maxlength="10" required>
                        <p class="hint">A returning patient is matched on this number.</p>
                    </div>
                    <div class="form-field">
                        <label for="email">Email</label>
                        <input class="input" type="email" id="email" name="email"
                               value="<c:out value='${formEmail}'/>"
                               placeholder="patient@gmail.com">
                    </div>
                </div>

            </div>
        </section>

        <section class="panel">
            <header class="panel__head"><h3>Appointment Details</h3></header>
            <div class="panel__body">

                <div class="form-field">
                    <label for="treatmentId">Treatment Type <span class="required">*</span></label>
                    <select class="input" id="treatmentId" name="treatmentId" required>
                        <option value="">Select a treatment</option>
                        <c:forEach var="treatment" items="${treatments}">
                            <option value="${treatment.treatmentId}"
                                    ${formTreatmentId eq treatment.treatmentId ? 'selected' : ''}>
                                <c:out value="${treatment.treatmentName}"/> -
                                LKR ${treatment.baseCost} (${treatment.estimatedMinutes} min)
                            </option>
                        </c:forEach>
                    </select>
                </div>

                <div class="form-field">
                    <label>Chosen Time <span class="required">*</span></label>
                    <p class="chosen-time" id="chosenTimeLabel">
                        <c:choose>
                            <c:when test="${not empty formTime}"><c:out value="${formTime}"/></c:when>
                            <c:otherwise>No time selected yet</c:otherwise>
                        </c:choose>
                    </p>
                    <p class="hint">Pick a green slot on the right.</p>
                </div>

                <div class="form-field">
                    <label for="notes">Notes</label>
                    <textarea class="input" id="notes" name="notes" rows="2"
                              placeholder="Anything the dentist should know"><c:out value="${formNotes}"/></textarea>
                </div>

                <div class="form-actions">
                    <a class="btn btn--ghost" href="${ctx}/admin/appointments">Cancel</a>
                    <button class="btn btn--primary" type="submit">Register Appointment</button>
                </div>

            </div>
        </section>
    </div>

    <%-- ---------- the generated slots ---------- --%>
    <div class="side-column">
        <section class="panel">
            <header class="panel__head">
                <h3>Available Times</h3>
                <span class="badge badge--muted">${chosenDate}</span>
            </header>
            <div class="panel__body">

                <c:choose>
                    <c:when test="${chosenDoctorId le 0}">
                        <div class="empty-state">
                            <p class="empty-state__title">Choose a dentist first</p>
                            <p class="empty-state__text">
                                Select a dentist and a date above, and the available
                                times for that day will appear here.
                            </p>
                        </div>
                    </c:when>

                    <c:when test="${empty slots}">
                        <div class="empty-state">
                            <p class="empty-state__title">Not working on this day</p>
                            <p class="empty-state__text">
                                This dentist has no working hours set for the chosen day.
                                Try another date, or ask an administrator to set the
                                working hours on the Schedule screen.
                            </p>
                        </div>
                    </c:when>

                    <c:otherwise>
                        <div class="slot-grid">
                            <c:forEach var="slot" items="${slots}">
                                <button type="button"
                                        class="slot-chip ${slot.available ? '' : 'slot-chip--booked'}"
                                        data-time="${slot.value}"
                                        onclick="selectSlot(this)">${slot.value}</button>
                            </c:forEach>
                        </div>

                        <div class="legend">
                            <span><i class="legend__dot legend__dot--free"></i> Available</span>
                            <span><i class="legend__dot legend__dot--booked"></i> Already booked</span>
                            <span><i class="legend__dot legend__dot--selected"></i> Selected</span>
                        </div>

                        <p class="hint">
                            A booked time cannot be selected. The server checks again
                            before saving, and the database refuses a duplicate as a
                            final safeguard.
                        </p>
                    </c:otherwise>
                </c:choose>

            </div>
        </section>
    </div>
</form>

<script src="${ctx}/assets/js/ui.js"></script>
<script>
    /* Shows the chosen time beside the form as well as in the hidden field. */
    document.addEventListener('click', function (event) {
        if (event.target.classList && event.target.classList.contains('slot-chip')
                && !event.target.classList.contains('slot-chip--booked')) {
            document.getElementById('chosenTimeLabel').textContent = event.target.dataset.time;
        }
    });

    document.getElementById('appointmentForm').addEventListener('submit', function (event) {
        if (!document.getElementById('appointmentTime').value) {
            event.preventDefault();
            showToast('Please choose a time slot before saving.', 'error');
        }
    });
</script>

<jsp:include page="/WEB-INF/views/layout/footer.jsp"/>
